name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: macos-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Test setup scripts
      run: make install
