name: CI

on:
  pull_request:
    types: [closed]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v1
    - name: Test setup scripts
      run: make install
